Lighten the load on macOS CI (#4859)

diff --git a/.github/workflows/nix-github-actions.yml b/.github/workflows/nix-github-actions.yml
--- a/.github/workflows/nix-github-actions.yml
+++ b/.github/workflows/nix-github-actions.yml
@@ -15,16 +15,20 @@ jobs:
       - id: set-matrix
         name: Generate Nix Matrix
         run: |
-          set -Eeu
-          matrix="$(nix eval --json '.#githubActions.matrix')"
-          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"
+          set -Eeuo pipefail
+          nix eval --json '.#githubActions.matrix' |
+            jq -c '.include |= map(select(any(.os[]; startswith("macos-")) | not))' |
+            cat <(echo -n matrix=) - >> "$GITHUB_OUTPUT"
 
+  # jvanburen 2025-10-08: our macOS CI capacity is limited, so i enabled fail-fast and
+  # disabled macos runners for now to help hopefully improve queueing time. we should
+  # revert these changes once we get more capacity
   nix-build:
     name: ${{ matrix.name }} (${{ matrix.system }})
     needs: nix-matrix
     runs-on: ${{ matrix.os }}
     strategy:
-      fail-fast: false
+      fail-fast: true
       matrix: ${{fromJSON(needs.nix-matrix.outputs.matrix)}}
     steps:
       - uses: actions/checkout@v4
